version: '3'

services:
  dbos:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: naman
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: backdrop

  ghostos:
    image: backdrop:latest
    restart: always
    links:
       - dbos:mysql
    ports:
      - 8080:80
    environment:
      BACKDROP_DB_HOST: dbos:3306
      BACKDROP_DB_USER: naman
      BACKDROP_DB_PASSWORD: root
      BACKDROP_DB_NAME: backdrop
    volumes:
      - backdrop_storage_new:/var/www/html

volumes:
   mysql_storage_new:
   backdrop_storage_new:
