version: '3'

services:
  dbos:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: naman
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: joomla

  joomlaos:
    image: joomla:3.9-php7.2-apache
    restart: always
    links:
       - joomladb:mysql
    ports:
      - 8081:81
    environment:
      JOOMLA_DB_HOST: dbos:3306
      JOOMLA_DB_USER: naman
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: joomla
    volumes:
      - joomla_storage_new:/var/www/html

volumes:
   mysql_storage_new:
   joomla_storage_new:
